{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd4cd8c5-d5c0-4dde-9566-30b626564e29",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: flask in ./.venv/lib/python3.14/site-packages (3.1.3)\n",
      "Requirement already satisfied: blinker>=1.9.0 in ./.venv/lib/python3.14/site-packages (from flask) (1.9.0)\n",
      "Requirement already satisfied: click>=8.1.3 in ./.venv/lib/python3.14/site-packages (from flask) (8.5.0)\n",
      "Requirement already satisfied: itsdangerous>=2.2.0 in ./.venv/lib/python3.14/site-packages (from flask) (2.2.0)\n",
      "Requirement already satisfied: jinja2>=3.1.2 in ./.venv/lib/python3.14/site-packages (from flask) (3.1.6)\n",
      "Requirement already satisfied: markupsafe>=2.1.1 in ./.venv/lib/python3.14/site-packages (from flask) (3.0.3)\n",
      "Requirement already satisfied: werkzeug>=3.1.0 in ./.venv/lib/python3.14/site-packages (from flask) (3.1.8)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m26.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m26.2.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/Users/rohankharade007/.venv/bin/python -m pip install --upgrade pip\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
      " * Running on http://127.0.0.1:5000\n",
      "\u001b[33mPress CTRL+C to quit\u001b[0m\n",
      "127.0.0.1 - - [20/Sep/2026 19:46:33] \"GET / HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "%pip install flask\n",
    "import os\n",
    "from flask import Flask, render_template_string, request, jsonify\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Extended Tesla Financial Data including Year-Wise Ratio History\n",
    "FINANCIAL_DATA = {\n",
    "    \"company_name\": \"Tesla, Inc.\",\n",
    "    \"ticker\": \"TSLA (NASDAQ)\",\n",
    "    \"ipo_date\": \"June 29, 2010 ($17/share)\",\n",
    "    \n",
    "    # Historical Year-wise Ratios\n",
    "    \"annual_ratios\": {\n",
    "        \"2010 (IPO)\": {\"pe\": \"N/A (Loss)\", \"ps\": \"25.4x\", \"pb\": \"8.2x\", \"roe\": \"-42.1%\"},\n",
    "        \"2012\":       {\"pe\": \"N/A (Loss)\", \"ps\": \"11.2x\", \"pb\": \"14.1x\", \"roe\": \"-78.5%\"},\n",
    "        \"2015\":       {\"pe\": \"N/A (Loss)\", \"ps\": \"7.8x\",  \"pb\": \"18.3x\", \"roe\": \"-81.2%\"},\n",
    "        \"2018\":       {\"pe\": \"N/A (Loss)\", \"ps\": \"2.6x\",  \"pb\": \"11.7x\", \"roe\": \"-21.3%\"},\n",
    "        \"2020 (1st Profitable Year)\": {\"pe\": \"1,100x\", \"ps\": \"22.5x\", \"pb\": \"33.8x\", \"roe\": \"4.8%\"},\n",
    "        \"2021\":       {\"pe\": \"190.5x\", \"ps\": \"18.1x\", \"pb\": \"28.1x\", \"roe\": \"21.1%\"},\n",
    "        \"2022\":       {\"pe\": \"38.2x\",  \"ps\": \"5.2x\",  \"pb\": \"9.4x\",  \"roe\": \"28.3%\"},\n",
    "        \"2023\":       {\"pe\": \"68.4x\",  \"ps\": \"8.1x\",  \"pb\": \"11.2x\", \"roe\": \"27.9%\"},\n",
    "        \"2024\":       {\"pe\": \"112.5x\", \"ps\": \"8.9x\",  \"pb\": \"10.8x\", \"roe\": \"11.2%\"},\n",
    "        \"2025\":       {\"pe\": \"135.2x\", \"ps\": \"9.8x\",  \"pb\": \"11.4x\", \"roe\": \"12.8%\"}\n",
    "    },\n",
    "\n",
    "    # Year-Wise Financial Matrix\n",
    "    \"annual_matrix\": {\n",
    "        \"2010 (IPO)\":  {\"revenue\": \"$116.7M\", \"net_income\": \"-$154.3M\", \"cash_flow\": \"-$128.0M\", \"margin\": \"-132.2%\"},\n",
    "        \"2012\":        {\"revenue\": \"$413.3M\", \"net_income\": \"-$396.2M\", \"cash_flow\": \"-$266.0M\", \"margin\": \"-95.8%\"},\n",
    "        \"2015\":        {\"revenue\": \"$4.05B\",  \"net_income\": \"-$888.7M\", \"cash_flow\": \"-$524.0M\", \"margin\": \"-21.9%\"},\n",
    "        \"2018\":        {\"revenue\": \"$21.46B\", \"net_income\": \"-$976.0M\", \"cash_flow\": \"+$2.10B\",  \"margin\": \"-4.5%\"},\n",
    "        \"2020\":        {\"revenue\": \"$31.54B\", \"net_income\": \"+$721.0M\", \"cash_flow\": \"+$5.94B\",  \"margin\": \"2.28%\"},\n",
    "        \"2021\":        {\"revenue\": \"$53.82B\", \"net_income\": \"+$5.52B\",  \"cash_flow\": \"+$11.50B\", \"margin\": \"10.25%\"},\n",
    "        \"2022\":        {\"revenue\": \"$81.46B\", \"net_income\": \"+$12.58B\", \"cash_flow\": \"+$14.72B\", \"margin\": \"15.45%\"},\n",
    "        \"2023\":        {\"revenue\": \"$96.77B\", \"net_income\": \"+$14.99B\", \"cash_flow\": \"+$13.25B\", \"margin\": \"15.49%\"},\n",
    "        \"2024\":        {\"revenue\": \"$97.69B\", \"net_income\": \"+$7.12B\",  \"cash_flow\": \"+$14.85B\", \"margin\": \"7.28%\"},\n",
    "        \"2025\":        {\"revenue\": \"$94.83B\", \"net_income\": \"+$3.81B\",  \"cash_flow\": \"+$14.75B\", \"margin\": \"4.01%\"}\n",
    "    },\n",
    "\n",
    "    \"balance_sheet\": {\n",
    "        \"Total Assets\": \"$122.07 Billion\",\n",
    "        \"Cash & Short Term Investments\": \"$36.56 Billion\",\n",
    "        \"Total Debt\": \"$8.38 Billion\",\n",
    "        \"Net Debt\": \"-$28.18 Billion (Net Cash Positive)\",\n",
    "        \"Total Equity\": \"$73.68 Billion\"\n",
    "    },\n",
    "\n",
    "    \"segments\": {\n",
    "        \"Automotive Sales & Leasing\": \"83.5%\",\n",
    "        \"Energy Generation & Storage\": \"8.5%\",\n",
    "        \"Services & Other\": \"8.0%\"\n",
    "    }\n",
    "}\n",
    "\n",
    "PREDEFINED_QUERIES = [\n",
    "    \"Show yearwise P/E ratio\",\n",
    "    \"Show yearwise ratios history\",\n",
    "    \"Show yearwise profit / net income\",\n",
    "    \"Show full yearwise financial matrix\",\n",
    "    \"When did Tesla list on NASDAQ?\",\n",
    "    \"What is Tesla's Balance Sheet overview?\"\n",
    "]\n",
    "\n",
    "def format_yearwise_ratios(ratio_type=\"pe\") -> str:\n",
    "    \"\"\"Formats year-by-year valuation ratios.\"\"\"\n",
    "    if ratio_type == \"pe\":\n",
    "        lines = [f\"• <b>{year}</b>: P/E Ratio = <b>{data['pe']}</b>\" for year, data in FINANCIAL_DATA[\"annual_ratios\"].items()]\n",
    "        return \"<b>Tesla Year-by-Year P/E Ratio Trend:</b><br><br>\" + \"<br>\".join(lines)\n",
    "    \n",
    "    lines = [f\"• <b>{year}</b> — P/E: {data['pe']} | P/S: {data['ps']} | P/B: {data['pb']} | ROE: {data['roe']}\" for year, data in FINANCIAL_DATA[\"annual_ratios\"].items()]\n",
    "    return \"<b>Tesla Year-by-Year Valuation Ratios History:</b><br><br>\" + \"<br>\".join(lines)\n",
    "\n",
    "def format_annual_matrix(metric_key=None, metric_label=None) -> str:\n",
    "    \"\"\"Formats annual financial metrics into HTML lists.\"\"\"\n",
    "    if metric_key and metric_label:\n",
    "        lines = [f\"• <b>{year}</b>: {data[metric_key]}\" for year, data in FINANCIAL_DATA[\"annual_matrix\"].items()]\n",
    "        return f\"<b>Tesla Yearwise {metric_label}:</b><br><br>\" + \"<br>\".join(lines)\n",
    "    \n",
    "    rows = [f\"• <b>{year}</b> — Revenue: {data['revenue']} | Net Income: {data['net_income']} | Cash Flow: {data['cash_flow']} | Margin: {data['margin']}\" for year, data in FINANCIAL_DATA[\"annual_matrix\"].items()]\n",
    "    return \"<b>Tesla Year-by-Year Financial Matrix (2010–2025):</b><br><br>\" + \"<br>\".join(rows)\n",
    "\n",
    "def contextual_chatbot(user_query: str, chat_history: list) -> str:\n",
    "    \"\"\"Enhanced query matching to support yearwise ratios and valuation trends.\"\"\"\n",
    "    query = user_query.strip().lower()\n",
    "\n",
    "    # 1. Yearwise Ratio / P/E queries\n",
    "    if (\"ratio\" in query or \"pe\" in query or \"p/e\" in query or \"valuation\" in query) and (\"year\" in query or \"annual\" in query or \"history\" in query or \"trend\" in query):\n",
    "        if \"pe\" in query or \"p/e\" in query:\n",
    "            return format_yearwise_ratios(\"pe\")\n",
    "        return format_yearwise_ratios(\"all\")\n",
    "\n",
    "    # 2. General P/E or Ratio query without explicit \"year\"\n",
    "    elif \"pe ratio\" in query or \"p/e ratio\" in query or \"pe\" in query:\n",
    "        return format_yearwise_ratios(\"pe\")\n",
    "\n",
    "    # 3. Yearwise Profit / Net Income\n",
    "    elif (\"profit\" in query or \"net income\" in query or \"income\" in query or \"earning\" in query) and (\"year\" in query or \"annual\" in query or \"history\" in query):\n",
    "        return format_annual_matrix(\"net_income\", \"Net Income / Profit\")\n",
    "\n",
    "    # 4. Yearwise Revenue\n",
    "    elif (\"revenue\" in query or \"sales\" in query) and (\"year\" in query or \"annual\" in query or \"history\" in query):\n",
    "        return format_annual_matrix(\"revenue\", \"Revenue\")\n",
    "\n",
    "    # 5. Yearwise Cash Flow\n",
    "    elif (\"cash flow\" in query or \"cashflow\" in query) and (\"year\" in query or \"annual\" in query or \"history\" in query):\n",
    "        return format_annual_matrix(\"cash_flow\", \"Operating Cash Flow\")\n",
    "\n",
    "    # 6. Full Financial Matrix\n",
    "    elif \"matrix\" in query or \"all metrics\" in query or \"full table\" in query or (\"yearwise\" in query and \"all\" in query):\n",
    "        return format_annual_matrix()\n",
    "\n",
    "    # 7. Balance Sheet & Segments\n",
    "    elif \"balance sheet\" in query or \"asset\" in query or \"debt\" in query or \"equity\" in query:\n",
    "        bs_str = \"<br>\".join([f\"• <b>{k}</b>: {v}\" for k, v in FINANCIAL_DATA[\"balance_sheet\"].items()])\n",
    "        return f\"<b>Tesla Balance Sheet Highlights:</b><br><br>{bs_str}\"\n",
    "\n",
    "    elif \"segment\" in query or \"breakdown\" in query:\n",
    "        seg_str = \"<br>\".join([f\"• <b>{k}</b>: {v}\" for k, v in FINANCIAL_DATA[\"segments\"].items()])\n",
    "        return f\"<b>Tesla Revenue Breakdown by Segment:</b><br><br>{seg_str}\"\n",
    "\n",
    "    # 8. Listing / IPO Date\n",
    "    elif \"list\" in query or \"ipo\" in query or \"nasdaq\" in query:\n",
    "        return f\"Tesla listed on NASDAQ on <b>{FINANCIAL_DATA['ipo_date']}</b> under ticker <b>{FINANCIAL_DATA['ticker']}</b>.\"\n",
    "\n",
    "    # 9. Fallback\n",
    "    else:\n",
    "        return (\n",
    "            \"Sorry, I couldn't recognize that exact request. Try asking for:<br>\"\n",
    "            \"• <b>Yearwise P/E Ratio</b><br>\"\n",
    "            \"• <b>Yearwise Ratios History</b><br>\"\n",
    "            \"• <b>Yearwise Profit</b><br>\"\n",
    "            \"• <b>Full Financial Matrix</b>\"\n",
    "        )\n",
    "\n",
    "# Embedded Single-Page Frontend HTML & CSS\n",
    "HTML_TEMPLATE = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "    <meta charset=\"UTF-8\">\n",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "    <title>Tesla Financial Screener Chatbot</title>\n",
    "    <style>\n",
    "        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }\n",
    "        body { background-color: #f1f5f9; display: flex; justify-content: center; align-items: center; height: 100vh; }\n",
    "        .chat-container { width: 580px; background: #ffffff; border-radius: 10px; box-shadow: 0 10px 25px rgba(0,0,0,0.08); display: flex; flex-direction: column; height: 700px; border: 1px solid #e2e8f0; }\n",
    "        .chat-header { background: #0f172a; color: #ffffff; padding: 16px 20px; border-top-left-radius: 10px; border-top-right-radius: 10px; font-size: 1.1rem; font-weight: 600; display: flex; align-items: center; justify-content: space-between; }\n",
    "        .chat-header span { font-size: 0.8rem; background: #e2e8f0; color: #0f172a; padding: 2px 8px; border-radius: 4px; }\n",
    "        .chat-box { flex: 1; padding: 20px; overflow-y: auto; display: flex; flex-direction: column; gap: 12px; background: #ffffff; }\n",
    "        .message { max-width: 88%; padding: 12px 16px; border-radius: 8px; font-size: 0.9rem; line-height: 1.5; }\n",
    "        .user-message { background: #2563eb; color: white; align-self: flex-end; border-bottom-right-radius: 2px; }\n",
    "        .bot-message { background: #f8fafc; color: #334155; align-self: flex-start; border: 1px solid #e2e8f0; border-bottom-left-radius: 2px; }\n",
    "        .presets { padding: 12px 16px; background: #f8fafc; border-top: 1px solid #e2e8f0; display: flex; flex-wrap: wrap; gap: 6px; }\n",
    "        .preset-btn { background: #ffffff; border: 1px solid #cbd5e1; padding: 6px 12px; border-radius: 6px; font-size: 0.78rem; color: #334155; cursor: pointer; font-weight: 500; transition: all 0.15s ease-in-out; }\n",
    "        .preset-btn:hover { background: #0f172a; color: white; border-color: #0f172a; }\n",
    "        .input-area { display: flex; padding: 14px; border-top: 1px solid #e2e8f0; background: #ffffff; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; }\n",
    "        .input-area input { flex: 1; padding: 10px 14px; border: 1px solid #cbd5e1; border-radius: 6px; outline: none; font-size: 0.9rem; }\n",
    "        .input-area button { background: #0f172a; color: white; border: none; padding: 10px 18px; margin-left: 8px; border-radius: 6px; cursor: pointer; font-weight: 600; }\n",
    "        .input-area button:hover { background: #1e293b; }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <div class=\"chat-container\">\n",
    "        <div class=\"chat-header\">\n",
    "            📈 Tesla (TSLA) Screener\n",
    "            <span>NASDAQ</span>\n",
    "        </div>\n",
    "        <div class=\"chat-box\" id=\"chat-box\">\n",
    "            <div class=\"message bot-message\">\n",
    "                Welcome to the <b>Tesla Financial Assistant</b> 🚗.<br><br>\n",
    "                Try asking:\n",
    "                <br>• <i>Show yearwise P/E ratio</i>\n",
    "                <br>• <i>Show yearwise ratios history</i>\n",
    "                <br>• <i>Show yearwise profit</i>\n",
    "            </div>\n",
    "        </div>\n",
    "        <div class=\"presets\">\n",
    "            {% for query in presets %}\n",
    "                <button class=\"preset-btn\" onclick=\"sendPreset('{{ query }}')\">{{ query }}</button>\n",
    "            {% endfor %}\n",
    "        </div>\n",
    "        <div class=\"input-area\">\n",
    "            <input type=\"text\" id=\"user-input\" placeholder=\"Ask about yearwise PE ratio, ratios history, profit...\" onkeypress=\"handleKeyPress(event)\">\n",
    "            <button onclick=\"sendMessage()\">Send</button>\n",
    "        </div>\n",
    "    </div>\n",
    "\n",
    "    <script>\n",
    "        let chatHistory = [];\n",
    "\n",
    "        function appendMessage(text, className) {\n",
    "            const chatBox = document.getElementById('chat-box');\n",
    "            const msgDiv = document.createElement('div');\n",
    "            msgDiv.className = `message ${className}`;\n",
    "            msgDiv.innerHTML = text;\n",
    "            chatBox.appendChild(msgDiv);\n",
    "            chatBox.scrollTop = chatBox.scrollHeight;\n",
    "        }\n",
    "\n",
    "        async function sendMessage() {\n",
    "            const input = document.getElementById('user-input');\n",
    "            const message = input.value.trim();\n",
    "            if (!message) return;\n",
    "\n",
    "            appendMessage(message, 'user-message');\n",
    "            input.value = '';\n",
    "\n",
    "            chatHistory.push({ role: 'user', text: message });\n",
    "\n",
    "            try {\n",
    "                const response = await fetch('/chat', {\n",
    "                    method: 'POST',\n",
    "                    headers: { 'Content-Type': 'application/json' },\n",
    "                    body: JSON.stringify({ message: message, history: chatHistory })\n",
    "                });\n",
    "                const data = await response.json();\n",
    "                \n",
    "                appendMessage(data.response, 'bot-message');\n",
    "                chatHistory.push({ role: 'bot', text: data.response });\n",
    "\n",
    "            } catch (error) {\n",
    "                appendMessage('Error reaching server.', 'bot-message');\n",
    "            }\n",
    "        }\n",
    "\n",
    "        function sendPreset(text) {\n",
    "            document.getElementById('user-input').value = text;\n",
    "            sendMessage();\n",
    "        }\n",
    "\n",
    "        function handleKeyPress(event) {\n",
    "            if (event.key === 'Enter') {\n",
    "                sendMessage();\n",
    "            }\n",
    "        }\n",
    "    </script>\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return render_template_string(HTML_TEMPLATE, presets=PREDEFINED_QUERIES)\n",
    "\n",
    "@app.route(\"/chat\", methods=[\"POST\"])\n",
    "def chat():\n",
    "    payload = request.json or {}\n",
    "    user_message = payload.get(\"message\", \"\")\n",
    "    chat_history = payload.get(\"history\", [])\n",
    "\n",
    "    bot_response = contextual_chatbot(user_message, chat_history)\n",
    "    return jsonify({\"response\": bot_response})\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True, use_reloader=False, port=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "748dad5e-82ac-4843-990c-f304eaf02eea",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "My Python Env",
   "language": "python",
   "name": "myenv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
